--- 
apiVersion: apps/v1 # API group we are sending out request to
kind: Deployment    # Kind of K8s objects we want to create
metadata:
  name: quote-service # Name of our deployment
  namespace: development    # Namespace the pods should be in
  labels:
    app: quote-service   # Label all pods in the group will have
spec:
  replicas: 2   # How many replicas of the container we want to run
  selector:
    matchLabels:
      app: quote-service
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      containers:   # specs of container to run in the pod
      - name: quote-container
        image: datawire/quote:0.5.0
        ports:
        - containerPort: 8080 # direct traffic for the container to port 8080

